### PR TITLE
Upgrade to Laravel 9

### PR DESCRIPTION
**Pull request by SimplyCorey**

### CODE REVIEW

**Comment by yepzy** [comment]
Hello @SimplyCorey 

I was upgrade a projet who's using this package to Laravel 9 and see this PR who look likes stuck this the 1st April


When do you think it will be merged ?


thanks in advance,

**Comment by SimplyCorey** [comment]
@yepzy Should be good to go.

**Comment by yepzy** [comment]
Hi @SimplyCorey  

I think you forget to update on packagist (https://packagist.org/packages/rsvpify/laravel-inky)

So when I want to update on composer I don't have the version 0.9 😅 

Could watch this please when you can ?

**Comment by SimplyCorey** [comment]
@yepzy should be good. https://packagist.org/packages/rsvpify/laravel-inky#v0.9.2

**Pull request merged**
